#!/bin/bash

#need to be in KPOINTConvergence directory
echo "Making kgridVals file"
kgrid-series ../POSCAR --min 0 | sed '/inf/d' | awk 'NR > 2 && ($2 > 0.15) {print $2 "\t" $3,$4,$5}' > kgridVals

while read grid
do
	label=${grid// /_}
	echo -n $grid
	grep "$grid" kgridVals | awk '{printf "," $1}'
	cd k$label
	grep TOTEN OUTCAR | tail -1 | awk '{print "," $5}'
	cd ..
done < kgrids > KPResults

echo "KPResults file has been created."
